markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Otávio Carvalho
url: http://otaviocarvalho.github.io
description: Act Small. Think big.
twitter: otaviocarvalho
github: otaviocarvalho
gravatar_url: http://www.gravatar.com/avatar/4e85ed39c33c7c8fc4e0374a68acd8e8
